import { defineArrayMember, defineField, defineType } from "sanity";

const indexedPaths = [
  { title: "Home", value: "/" },
  { title: "About", value: "/about" },
  { title: "Our Team", value: "/about/our-team" },
  { title: "Physicians", value: "/about/physicians" },
  { title: "Dietitians", value: "/about/dietitians" },
  { title: "Surgery Center", value: "/about/surgery-center" },
  { title: "History", value: "/about/history" },
  { title: "Locations", value: "/about/locations" },
  { title: "Medications", value: "/medications" },
  { title: "Bariatric Metrics", value: "/bariatric-metrics" },
  { title: "Contact", value: "/contact" },
  { title: "Patient Stories", value: "/patient-stories" },
  { title: "FMLA Paperwork", value: "/fmla-short-term-disability-paperwork" },
  { title: "Shop", value: "/shop" },
  { title: "Cart", value: "/shop/cart" },
  { title: "Blog Index", value: "/blog" },
  { title: "Legacy Blog Index", value: "/blog/legacy" },
];

export const reactPageOverride = defineType({
  name: "reactPageOverride",
  title: "React Page Override",
  type: "document",
  groups: [
    { name: "content", title: "Editable content", default: true },
    { name: "seo", title: "SEO" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({ name: "title", title: "Admin title", type: "string", group: "settings", validation: (rule) => rule.required().max(120) }),
    defineField({
      name: "path",
      title: "React page URL",
      type: "string",
      group: "settings",
      description: "These pages are still React-coded. This document can override metadata and add managed content blocks.",
      options: { list: indexedPaths, layout: "dropdown" },
      validation: (rule) => rule.required().regex(/^\/(?:[a-z0-9-]+\/?)*$/, { name: "absolute path" }),
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      group: "settings",
      options: { list: [{ title: "Active", value: "active" }, { title: "Draft", value: "draft" }, { title: "Archived", value: "archived" }], layout: "radio" },
      initialValue: "active",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "adminWarning",
      title: "Editor warning",
      type: "text",
      rows: 3,
      group: "settings",
      initialValue: "This is a React-coded page. You can edit SEO and managed content blocks here, but layout, core widgets, forms, and complex page sections still require code changes.",
      validation: (rule) => rule.max(400),
    }),
    defineField({ name: "eyebrow", title: "Managed eyebrow", type: "string", group: "content", validation: (rule) => rule.max(80) }),
    defineField({ name: "headline", title: "Managed headline", type: "string", group: "content", validation: (rule) => rule.max(140) }),
    defineField({ name: "summary", title: "Managed summary", type: "text", rows: 4, group: "content", validation: (rule) => rule.max(700) }),
    defineField({
      name: "contentBlocks",
      title: "Additional editable content blocks",
      type: "array",
      group: "content",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({ name: "heading", title: "Heading", type: "string", validation: (rule) => rule.max(140) }),
            defineField({ name: "body", title: "Body", type: "text", rows: 5, validation: (rule) => rule.max(1200) }),
            defineField({
              name: "link",
              title: "Optional link",
              type: "object",
              fields: [
                defineField({ name: "label", title: "Label", type: "string", validation: (rule) => rule.max(80) }),
                defineField({ name: "href", title: "URL", type: "url", validation: (rule) => rule.uri({ scheme: ["http", "https", "mailto", "tel"], allowRelative: true }) }),
              ],
            }),
          ],
          preview: { select: { title: "heading", subtitle: "body" } },
        }),
      ],
      validation: (rule) => rule.max(6),
    }),
    defineField({ name: "seoTitle", title: "SEO title", type: "string", group: "seo", validation: (rule) => rule.max(70) }),
    defineField({ name: "seoDescription", title: "SEO description", type: "text", rows: 3, group: "seo", validation: (rule) => rule.max(170) }),
    defineField({ name: "focusKeyword", title: "Primary keyword", type: "string", group: "seo", validation: (rule) => rule.max(80) }),
    defineField({ name: "canonicalUrl", title: "Canonical URL", type: "url", group: "seo", validation: (rule) => rule.uri({ scheme: ["http", "https"], allowRelative: false }) }),
    defineField({
      name: "robots",
      title: "Robots",
      type: "string",
      group: "seo",
      options: { list: [{ title: "Index, follow", value: "index,follow" }, { title: "Noindex, follow", value: "noindex,follow" }, { title: "Noindex, nofollow", value: "noindex,nofollow" }], layout: "radio" },
      initialValue: "index,follow",
    }),
    defineField({ name: "ogTitle", title: "Open Graph title", type: "string", group: "seo", validation: (rule) => rule.max(70) }),
    defineField({ name: "ogDescription", title: "Open Graph description", type: "text", rows: 3, group: "seo", validation: (rule) => rule.max(170) }),
    defineField({ name: "ogImage", title: "Open Graph image", type: "image", group: "seo", options: { hotspot: true } }),
    defineField({ name: "structuredDataType", title: "Structured data type", type: "string", group: "seo", options: { list: ["WebPage", "MedicalWebPage", "AboutPage", "ContactPage", "CollectionPage"], layout: "dropdown" }, initialValue: "WebPage" }),
  ],
  preview: {
    select: { title: "title", subtitle: "path", status: "status" },
    prepare: ({ title, subtitle, status }) => ({ title: title || subtitle || "React page override", subtitle: [subtitle, status].filter(Boolean).join(" - ") }),
  },
});
